version: '3.8'
services:
  grade_mysql:
    image: mysql:8.0
    ports:
      - '3306'
    container_name: grade_mysql_server
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: grade_root_password
      MYSQL_DATABASE: grade_database
      MYSQL_USER: grade_user
      MYSQL_PASSWORD: grade_user_password
    volumes:
      - './volume:/var/lib/mysql'
    networks:
      - grade_network

  grade_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: grade_phpmyadmin_container
    environment:
      PMA_HOST: grade_mysql_server
      PMA_USER: grade_user
      PMA_PASSWORD: grade_user_password
      PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d
      UPLOAD_LIMIT: 100000000
    ports:
      - "${PHPMYADMIN_PORT-8080}:80"
    networks:
      - grade_network

  grade_nginx:
    image: nginx:latest
    container_name: grade_container
    ports:
      - "${NGINX_PORT-8001}:8001"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ../:/var/www/grade
    networks:
      - grade_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grade_php:
    container_name: grade_app
    image: php-scout4
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ../:/var/www/grade
      - ./php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - grade_network


networks:
  grade_network:
    driver: bridge
volumes:
  grade_mysql:
    driver: local
